apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2016-09-28T15:08:22Z
  generation: 3
  labels:
    name: 911bot
  name: 911bot-deployment
  namespace: surge-admin-infra
  resourceVersion: "15041827"

  selfLink: /apis/extensions/v1beta1/namespaces/surge-admin-infra/deployments/911bot-deployment
  uid: 658cb448-858d-11e6-be94-0af422f9535d
spec:
  paused: true
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      name: 911bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:

    metadata:
      creationTimestamp: null
      labels:
        name: 911bot
    spec:
      containers:
      - env:
        - name: SLACKBOT_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: apitoken
              name: surge-911bot-slackapi
        image: quay.io/surgeforward/911bot
        imagePullPolicy: Always
        name: 911bot
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /contacts
          name: contacts-persistent-storage
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: surgeforward-surgecodemonkey-pull-secret
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/surge/911bot/contacts
        name: contacts-persistent-storage
status:
  availableReplicas: 1
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
